# Generated by Django 4.2.1 on 2023-06-26 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_talk_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_content', models.CharField(max_length=2048)),
            ],
        ),
        migrations.AlterField(
            model_name='talk_content',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.content'),
        ),
    ]
