# Generated by Django 4.2.1 on 2023-06-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_content_talk_content_chat_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk_content',
            name='chat_content',
            field=models.CharField(max_length=2048),
        ),
    ]
